# Generated by Django 3.2.7 on 2022-02-12 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系方式')),
                ('advice', models.CharField(max_length=256, verbose_name='建议')),
                ('remarks', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '反馈建议',
                'verbose_name_plural': '反馈建议',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('desc', models.CharField(max_length=120, verbose_name='简述')),
                ('content', mdeditor.fields.MDTextField()),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门博客')),
                ('img', models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to='blog/cover/', verbose_name='图片地址')),
                ('is_origin', models.BooleanField(default=True, verbose_name='是否原创')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'db_table': 'blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='专栏名')),
                ('remarks', models.CharField(blank=True, default=None, max_length=8192, null=True, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类专栏',
                'verbose_name_plural': '分类专栏',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=12, verbose_name='标签名称')),
                ('bkc', models.CharField(default='#7fd5ea', max_length=12, verbose_name='背景色')),
                ('blog', models.ManyToManyField(related_name='blog_tag_list', to='blogsite.Blog', verbose_name='关联博客')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'blog_Tag',
            },
        ),
        migrations.CreateModel(
            name='LoveRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='具体对象id')),
                ('is_valid', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联的模型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_love_list', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'Love_related',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('temporary', models.CharField(blank=True, max_length=32, null=True, verbose_name='临时用户名')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_list', to='blogsite.blog', verbose_name='关联博客')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='blogsite.comment', verbose_name='评论的回复')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_list', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'blog_comment',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_blog_list', to='blogsite.category', verbose_name='关联分类专栏'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_list', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
