# Generated by Django 3.2.7 on 2022-02-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog_blog',
        ),
    ]
