# Generated by Django 3.2.7 on 2022-02-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_alter_blog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adviceupload',
            table='blog_advice',
        ),
        migrations.AlterModelTable(
            name='category',
            table='blog_category',
        ),
    ]
