# Generated by Django 3.2.7 on 2022-02-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_auto_20220212_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='temporary',
        ),
    ]
