# Generated by Django 3.2.7 on 2022-02-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0005_alter_category_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keyword',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='关键词'),
        ),
    ]
