# Generated by Django 3.2.7 on 2022-02-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_avatar.jpg', max_length=120, null=True, upload_to='auth/avatar/', verbose_name='头像地址'),
        ),
    ]
